apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP # Default type; makes the service internal to the cluster
  selector:
    app: web-backend # Matches the label in the Deployment template
  ports:
    - protocol: TCP
      port: 8080 # The port that the Service itself exposes inside the cluster
      targetPort: 80  # The port on the Pod/Container where traffic is sent
