# -- Environnement de déploiement
environment: production
# -- URL des paquets de l'application
imageRegistry: ghcr.io/gayasystem/lewindigo
host:
  # -- Nom de domaine de l'application
  name: "lewindigo.org"
  # -- Chemin de l'URL ou déployer l'application
  path: "/"
