apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-middleware-chain@kubernetescrd
spec:
  ingressClassName: reverse-proxy
  rules:
    {{- if .Values.host.name }}
    - host: {{ .Values.host.name | quote }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.host.path }}
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  name: http
