apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-http   # <-- The Service will look for this label
  template:
    metadata:
      labels:
        app: web-http
    spec:
      containers:
        - name: lewindigo
          {{- if eq .Values.environment "production" }}
          image: {{ .Values.imageRegistry }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          {{- else if eq .Values.environment "development" }}
          image: {{ .Values.imageRegistry }}:latest
          imagePullPolicy: Never
          {{- end }}
          ports:
            - containerPort: 80 # <-- Your application port inside the pod
