apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: lewindigo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      serviceAccountName: lewindigo-sa
      containers:
        - name: www
          image: ghcr.io/gayasystem/lewindigo:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: lewindigo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      serviceAccountName: dummy-sa
      automountServiceAccountToken: false
      containers:
        - name: dummy
          image: traefik/whoami:v1.10.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
