apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www
  namespace: lewindigo
spec:
  ingressClassName: reverse-proxy
  rules:
    - host: lewindigo.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: www
                port:
                  number: 80
    - host: www.lewindigo.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: www
                port:
                  number: 80
