apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-canonical
  namespace: lewindigo
spec:
  redirectRegex:
    regex: ^https?://(www\.)?le-windigo\.org/(.*)
    replacement: https://lewindigo.org/$2
    permanent: true
