apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware
  namespace: {{ .Release.Namespace }}
spec:
  replacePathRegex:
    regex: "^{{ .Values.host.path }}/(.*)"
    replacement: "/$1"
