apiVersion: v1
kind: Service
metadata:
  name: lewindigo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: web-http     # <-- Connects to the Pods matching this label
  ports:
    - protocol: TCP
      port: 8080      # <-- The port the service listens on inside the cluster
      targetPort: 80  # <-- The port on the pod where traffic is sent
  type: ClusterIP     # <-- Default type (internal only)