apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: lewindigo
spec:
  type: ClusterIP
  selector:
    app: www
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy
  namespace: lewindigo
spec:
  selector:
    app: dummy
  ports:
    - port: 80
      targetPort: 80
